config/routes.rb
Rails.application.routes.draw do
  root 'pins#index'

  devise_for :users
  resource :token, only: [:show]
  resources :pins, only: [:index, :new, :create]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :pins, only: [:index, :create]
    end
  end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :generate_token

  private
    def generate_token
      self.api_token ||= SecureRandom.hex if new_record?
    end
end

app/controllers/api/v1/pins_controller.rb
class Api::V1::PinsController < ApplicationController
  
  before_action :authenticate
  
  def index
    render json: Pin.all.order('created_at DESC')
  end

  def create
    pin = Pin.new(pin_params)
    if pin.save
      render json: pin, status: 201
    else
      render json: { errors: pin.errors }, status: 422
    end
  end

  private
    def pin_params
      params.require(:pin).permit(:title, :image_url)
    end
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  def authenticate
    user = User.find_by(email: request.headers['HTTP_X_USER_EMAIL'])
    acces = user ? request.headers['X-API-TOKEN'] == user.api_token : false
      
    unless acces
      render json: { errors: "Acceso denegado" }, status: 401
    end
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def new
    @pin = Pin.new
  end

  def create
    pin = Pin.new(pin_params)
    pin.user = current_user
    if pin.save
      redirect_to root_path, notice: "El pin fue creado exitosamente"
    else
      render :new
    end
  end

  private
    def pin_params
      params.require(:pin).permit(:title, :image_url)
    end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pinterest Clone", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><%= link_to "Nuevo Pin", new_pin_path %></li>
            <li><%= link_to "API Token", token_path, remote: true %></li>
            <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Registrarse", new_user_registration_path %></li>
            <li><%= link_to "Ingresar", new_user_session_path %></li>
          <% end  %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Nuevo Pin</h1>

      <%= form_for @pin do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Ingresa el título" %>
        </div>
        <div class="form-group">
          <%= f.url_field :image_url, class: "form-control input-lg", placeholder: "Ingresa la URL de la imagen" %>
        </div>

        <div class="action">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled clearfix masonry">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <div class="panel-body">
        <img src="<%= pin.image_url %>" alt="<%= pin.title %>">
        <h2><%= pin.title %></h2>
        <% if pin.user %>
        <p class="user">Submitted by <%= pin.user.email %></p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<%= render 'form' %>

app/views/tokens/_show.html.erb
<div id="token-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">API Token</h4>
      </div>
      <div class="modal-body">
        <p>El siguiente es el token que debes utilizar para hacer llamados a través del API. Por seguridad mantenlo privado:</p>

        <div class="well text-center" style="font-size: 21px"><%= current_user.api_token %></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/tokens/show.js.erb
$('<%= j render "show" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();